// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


float temp_sensor_one;
float temp_sensor_two;

void initProperties(){

  ArduinoCloud.addProperty(temp_sensor_one, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp_sensor_two, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
